view: activity {
  label: "Activity & Engagement"
  # Search, answer, click, feedback and page-visit activity. These arrive on the
  # USER_EVENT and GWS_LOG rows, broken down by device. Slice by device_type to
  # compare desktop vs other clients.
  #
  # USER_EVENT / GWS_LOG slice of export_history, filtered to rows with a device.
  # The slice is applied as a sql_always_where on the explore so BigQuery reads
  # the partitioned base table directly rather than a derived-table subquery.
  sql_table_name: `@{gemini_project}.@{gemini_dataset}.export_history` ;;

  dimension: data_source {
    hidden: yes
    description: "AGGREGATED_METRIC, GWS_LOG, or USER_EVENT. Used to slice this view at the explore level."
    type: string
    sql: ${TABLE}.data_source ;;
  }

  dimension: pk {
    primary_key: yes
    hidden: yes
    sql: CONCAT(${TABLE}.engine_id, '|', ${TABLE}.metric_date, '|', ${TABLE}.data_source, '|', ${TABLE}.device_type) ;;
  }

  dimension: engine_id {
    description: "Gemini Enterprise engine (app) the activity belongs to."
    type: string
    sql: ${TABLE}.engine_id ;;
  }

  dimension: app_name {
    label: "App"
    description: "Friendly name of the Gemini Enterprise app, mapped from engine_id."
    type: string
    sql: ${TABLE}.app_name ;;
  }

  dimension_group: metric {
    label: "Metric"
    description: "Date (UTC) the activity was recorded for."
    type: time
    timeframes: [date, week, month, quarter, year]
    convert_tz: no
    datatype: date
    sql: ${TABLE}.metric_date ;;
  }

  dimension: device_type {
    description: "Client platform the activity came from, derived from the user agent (e.g. Macintosh, X11, Rest)."
    type: string
    sql: ${TABLE}.device_type ;;
  }

  measure: searches {
    description: "Total search queries issued."
    type: sum
    sql: ${TABLE}.search_count ;;
    value_format_name: decimal_0
  }

  measure: search_clicks {
    description: "Total clicks on search results."
    type: sum
    sql: ${TABLE}.search_click_count ;;
    value_format_name: decimal_0
  }

  measure: click_through_rate {
    label: "Search Click-Through Rate"
    description: "Search clicks divided by searches. Higher means results are more relevant."
    type: number
    sql: SAFE_DIVIDE(${search_clicks}, ${searches}) ;;
    value_format_name: percent_1
  }

  measure: answers {
    label: "Assistant Answers"
    description: "Total answers generated by the Assistant."
    type: sum
    sql: ${TABLE}.answer_count ;;
    value_format_name: decimal_0
  }

  measure: actions {
    description: "Total user actions recorded on the engine (interactions beyond search and answers)."
    type: sum
    sql: ${TABLE}.action_count ;;
    value_format_name: decimal_0
  }

  measure: likes {
    description: "Total positive (thumbs-up) feedback responses on answers."
    type: sum
    sql: ${TABLE}.feedback_like_count ;;
    value_format_name: decimal_0
  }

  measure: dislikes {
    description: "Total negative (thumbs-down) feedback responses on answers."
    type: sum
    sql: ${TABLE}.feedback_dislike_count ;;
    value_format_name: decimal_0
  }

  measure: positive_feedback_rate {
    description: "Likes divided by total feedback (likes + dislikes). A quality signal for Assistant answers."
    type: number
    sql: SAFE_DIVIDE(${likes}, NULLIF(${likes} + ${dislikes}, 0)) ;;
    value_format_name: percent_1
  }

  measure: home_page_visits {
    description: "Total visits to the Gemini Enterprise home page."
    type: sum
    sql: ${TABLE}.total_home_page_visit_count ;;
    value_format_name: decimal_0
  }

  measure: agent_page_visits {
    description: "Total visits to individual agent pages."
    type: sum
    sql: ${TABLE}.total_agent_page_visit_count ;;
    value_format_name: decimal_0
  }

  measure: agent_gallery_page_visits {
    description: "Total visits to the agent gallery (where users browse available agents)."
    type: sum
    sql: ${TABLE}.total_agent_gallery_page_visit_count ;;
    value_format_name: decimal_0
  }

  measure: prompts_page_visits {
    description: "Total visits to the prompts page (saved/shared prompt library)."
    type: sum
    sql: ${TABLE}.total_prompts_page_visit_count ;;
    value_format_name: decimal_0
  }

  measure: notebook_lm_page_visits {
    label: "NotebookLM Page Visits"
    description: "Total visits to the NotebookLM page."
    type: sum
    sql: ${TABLE}.total_notebook_lm_page_visit_count ;;
    value_format_name: decimal_0
  }

  measure: deep_research_page_visits {
    description: "Total visits to the Deep Research page."
    type: sum
    sql: ${TABLE}.total_deep_research_page_visit_count ;;
    value_format_name: decimal_0
  }

  measure: idea_generation_page_visits {
    description: "Total visits to the idea generation page."
    type: sum
    sql: ${TABLE}.total_idea_generation_page_visit_count ;;
    value_format_name: decimal_0
  }
}
